### ISSUE TITLE
There is a small probability that the length of the signature is less than the public key size

### ISSUE THREAD

**Issue by yrdsm666** [niclabs/libtc-rsa#4]
The problem of https://github.com/niclabs/tcrsa/issues/1 still exists.
When I generate a large number of signatures, there may occasionally be some signatures with shorter lengths.

**Comment by eriverosr** [comment]
Thanks for the report! How many signatures are you generating? (just to know how many signatures I need to generate to replicate the problem)

I would be grateful if you can attach the code you are using to generate them.

**Comment by yrdsm666** [comment]
This bug has actually been resolved in https://github.com/niclabs/tcrsa/issues/1.
